/**
 * Meta hero pool by position.
 *
 * Source of truth = `src/data/meta-stats.json` (regenerated by
 * `scripts/fetch-stratz-meta.js`). When that file is missing or empty for a
 * given position, we fall back to the hand-curated `META_FALLBACK` below so
 * the UI is never empty.
 *
 * Heroes are referenced by OpenDota `shortName` (= `name` minus the
 * `npc_dota_hero_` prefix). Resolve to `Hero` objects at runtime via the
 * `useHeroes()` map.
 */
import metaStatsJson from './meta-stats.json'

export type MetaPosition = 1 | 2 | 3 | 4 | 5

export interface MetaHeroStat {
  shortName: string
  matchCount: number
  winCount: number
}

/**
 * Fallback list of meta heroes per position, used when stats JSON is missing.
 * Names follow the OpenDota internal `shortName` convention (e.g. Anti-Mage =
 * `antimage`, Wraith King = `skeleton_king`, Magnus = `magnataur`).
 */
const META_FALLBACK: Record<MetaPosition, string[]> = {
  // Carry
  1: [
    'phantom_assassin', 'juggernaut', 'antimage', 'spectre', 'faceless_void',
    'slark', 'terrorblade', 'skeleton_king', 'ursa', 'riki', 'morphling',
    'luna', 'medusa', 'drow_ranger', 'life_stealer', 'naga_siren',
    'phantom_lancer', 'troll_warlord', 'sven', 'alchemist',
  ],
  // Mid
  2: [
    'invoker', 'storm_spirit', 'ember_spirit', 'void_spirit', 'queenofpain',
    'nevermore', 'puck', 'tinker', 'templar_assassin', 'death_prophet',
    'huskar', 'lina', 'pugna', 'arc_warden', 'dragon_knight', 'viper',
    'razor', 'kez', 'ringmaster',
  ],
  // Offlane
  3: [
    'mars', 'primal_beast', 'shredder', 'magnataur', 'centaur', 'tidehunter',
    'axe', 'bristleback', 'legion_commander', 'doom_bringer', 'dark_seer',
    'night_stalker', 'abyssal_underlord', 'beastmaster', 'pangolier',
    'enigma', 'abaddon', 'sand_king', 'brewmaster',
  ],
  // Soft support
  4: [
    'tusk', 'earth_spirit', 'earthshaker', 'mirana', 'pudge', 'bounty_hunter',
    'spirit_breaker', 'nyx_assassin', 'monkey_king', 'snapfire', 'ogre_magi',
    'dawnbreaker', 'marci', 'hoodwink', 'silencer', 'elder_titan',
    'rattletrap',
  ],
  // Hard support
  5: [
    'crystal_maiden', 'lion', 'shadow_shaman', 'jakiro', 'warlock',
    'witch_doctor', 'vengefulspirit', 'treant', 'undying', 'dazzle', 'wisp',
    'oracle', 'winter_wyvern', 'skywrath_mage', 'grimstroke', 'bane',
    'disruptor', 'rubick', 'omniknight', 'keeper_of_the_light',
  ],
}

type StatsFile = Partial<Record<'1' | '2' | '3' | '4' | '5', MetaHeroStat[]>>

const stats = metaStatsJson as StatsFile

/**
 * Returns the meta pool for a position as a list of hero `shortName`s.
 * Prefers JSON stats (if present), otherwise falls back to the curated list.
 */
export function getMetaPool(pos: MetaPosition): string[] {
  const fromJson = stats[String(pos) as keyof StatsFile]
  if (fromJson && fromJson.length > 0) {
    return fromJson.map((e) => e.shortName)
  }
  return META_FALLBACK[pos]
}

/**
 * Returns full stats entries for a position (or empty when JSON missing).
 * Useful for displaying pickrate/winrate next to a hero in the UI.
 */
export function getMetaStats(pos: MetaPosition): MetaHeroStat[] {
  return stats[String(pos) as keyof StatsFile] ?? []
}

/**
 * `true` when JSON stats are loaded — UI can show "live data" badge.
 */
export const HAS_LIVE_META_STATS = Object.values(stats).some(
  (arr) => Array.isArray(arr) && arr.length > 0,
)
